#!/bin/sh
#  ____ ____  ______        ____  __ 
# | __ ) ___||  _ \ \      / /  \/  |
# |  _ \___ \| |_) \ \ /\ / /| |\/| |
# | |_) |__) |  __/ \ V  V / | |  | |
# |____/____/|_|     \_/\_/  |_|  |_|
#
# --- Author: CaptainEureka
# --- GitHub: https://github.com/CaptainEureka
# --- A customized bspwmrc

#### AUTO START ####
function run {
  if [ ! $(pgrep -f $1) ] ;
  then
    $@&
  fi
}

run sxhkd
run launch-polybar bspwm
picom --experimental-backends &
run libinput-gestures
run launch-notif-center
setbg -r &
pgrep xob || xob-volume-watcher.py | xob -s pywal &
run mopidy
run flashfocus

#### MONITORS ####
bspc monitor $(bspc query --monitors --names) -d 1 2 3 4 5
bspc config remove_disabled_monitors  true
bspc config remove_unplugged_monitors true

#### BSPWM CONFIG ####
bspc config border_width        4
bspc config border_radius       0
bspc config window_gap          20
bspc config top_padding         54
bspc config bottom_padding      0
bspc config right_padding       0
bspc config left_padding        0

xsetroot -cursor_name left_ptr
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner 

bspc config split_ratio             0.5
bspc config initial_polarity        second_child
bspc config automatic_scheme        alternate
bspc config borderless_monocle      true
bspc config gapless_monocle         false
bspc config focus_follows_pointer   true
bspc config click_to_focus          button1 
bspc config single_monocle          true

#### BSPWM COLORS ####

# source pywal colors
. "${HOME}/.cache/wal/colors.sh"
bspc config normal_border_color     "$color8"
bspc config active_border_color     "$color8"
bspc config focused_border_color    "$color6"
bspc config presel_feedback_color   "$color6"
bspc config urgent_border_color     "$color1"

#### BSPWM WINDOW RULES ####
bspc rule -a Gimp desktop='^7' state=floating follow=on
bspc rule -a 'Firefox Beta' desktop='^2'
bspc rule -a firefox desktop='^2'
bspc rule -a Chromium desktop='^2'
bspc rule -a ark state=floating
bspc rule -a Screenkey manage=off
bspc rule -a feh desktop='^4' state=floating
bspc rule -a Thunar desktop='^4' state=floating
bspc rule -a Sxiv state=floating rectangle=$(bsp-rectangle 1920 1080)
bspc rule -a dolphin desktop='^4' state=floating rectangle=$(bsp-rectangle 1920 1080)
bspc rule -a Xephyr desktop='^5'
